### ISSUE TITLE
An error occurred in Pixi task wandb: ERROR Internal wandb error: file data was not synced

### ISSUE THREAD

**Issue by lucky339aue** [KTH-RPL/neural_graph_mapping#3]
```
✨ Pixi task (nrgbd_br in default): python -m neural_graph_mapping.run_mapping --config nrgbd_dataset.yaml neural_graph_map.yaml coslam_eval.yaml --dataset_config.root_dir $NGM_DATA_DIR/nrgbd/ --dataset_config.scene breakfast_room $NGM_EXTRA_ARGS --rerun_vis True
/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 32 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
wandb: Currently logged in as: xinnanxinnan944 (xingnan_001). Use `wandb login --relogin` to force relogin
Thread HandlerThread:wandb.init()...
Traceback (most recent call last):
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 99, in _run
    self._process(record)
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 278, in _process
    self._hm.handle(record)
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 150, in handle
    handler(record)
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 160, in handle_request
    handler(record)
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 702, in handle_request_run_start
    self._system_monitor.probe(publish=True)
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in probe
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in <listcomp>
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/gpu.py", line 395, in probe
    info["gpu"] = pynvml.nvmlDeviceGetName(pynvml.nvmlDeviceGetHandleByIndex(0))  # type: ignore
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/vendor/pynvml/pynvml.py", line 1962, in wrapper
    return res.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
wandb: ERROR Internal wandb error: file data was not synced
wandb: ERROR transport failed
Traceback (most recent call last):
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xingbei_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 2428, in <module>
    main()
  File "/home/xingbei_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 2421, in main
    neural_graph_map.fit()
  File "/home/xingbei_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 1036, in fit
    run = wandb.init(
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
Traceback (most recent call last):
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xingbei_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 2428, in <module>
    main()
  File "/home/xingbei_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 2421, in main
    neural_graph_map.fit()
  File "/home/xingbei_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 1036, in fit
    run = wandb.init(
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/xingbei_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
wandb: While tearing down the service manager. The following error has occurred: [Errno 32] Broken pipe
``` 
Error in wsl2

**Comment by roym899** [comment]
Maybe try to disable wandb to see if that fixes the issue `wandb disabled`

**Comment by roym899** [comment]
Seems like it might be an Nvidia driver issue: https://github.com/wandb/wandb/issues/7683#issuecomment-2124952404

**Comment by lucky339aue** [comment]
Hello, I use `wandb disabled`
, it seems to work, but a new error appears
```
✨ Pixi task (nrgbd_br in default): python -m neural_graph_mapping.run_mapping --config nrgbd_dataset.yaml neural_graph_map.yaml coslam_eval.yaml --dataset_config.root_dir $NGM_DATA_DIR/nrgbd/ --dataset_config.scene breakfast_room $NGM_EXTRA_ARGS --rerun_vis True
/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 32 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
  2%|█▌                                                                       | 24/1167 [00:04<03:10,  5.99it/s]
Traceback (most recent call last):
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 2428, in <module>
    main()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 2421, in main
    neural_graph_map.fit()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 1108, in fit
    self._current_frame_optimization()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/utils.py", line 83, in wrapper
    result = f(*args, **kwargs)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 1252, in _current_frame_optimization
    self._log(loss_dict)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 1759, in _log
    self._extract_mesh(
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 2380, in _extract_mesh
    rr.Mesh3D(
TypeError: Mesh3DExt.__init__() got an unexpected keyword argument 'indices'
Traceback (most recent call last):
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 2428, in <module>
    main()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 2421, in main
    neural_graph_map.fit()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 1108, in fit
    self._current_frame_optimization()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/utils.py", line 83, in wrapper
    result = f(*args, **kwargs)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 1252, in _current_frame_optimization
    self._log(loss_dict)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 1759, in _log
    self._extract_mesh(
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 2380, in _extract_mesh
    rr.Mesh3D(
TypeError: Mesh3DExt.__init__() got an unexpected keyword argument 'indices'
```

**Comment by lucky339aue** [comment]
At line 2378 of run_mapping.py
Comment
```
 if log_to_rerun:
            mesh = slam_dataset.Mesh(
                vertices=all_verts, indices=all_faces, vertex_colors=all_vert_colors / 255
            )
            simplify_resolution = resolution + 0.01
            while len(mesh.vertices) > 5000000:
                print("Simplifying mesh for Rerun vis")
                mesh.simplify(simplify_resolution)
                simplify_resolution += 0.01

            # rr.log(
            #     "mesh",
            #     rr.Mesh3D(
            #         vertex_positions=mesh.vertices,
            #         indices=mesh.face_indices,
            #         vertex_colors=mesh.vertex_colors,
            #     ),
            # )
```

**Comment by roym899** [comment]
I pushed a new commit including the previous fixes and hopefully also a fix for this issue. Let me know if it works.
