### ISSUE TITLE
OSError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lucky339aue** [KTH-RPL/neural_graph_mapping#4]
✨ Pixi task (nrgbd_br in default): python -m neural_graph_mapping.run_mapping --config nrgbd_dataset.yaml neural_graph_map.yaml coslam_eval.yaml --dataset_config.root_dir $NGM_DATA_DIR/nrgbd/ --dataset_config.scene breakfast_room $NGM_EXTRA_ARGS --rerun_vis True
Traceback (most recent call last):
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 18, in <module>
    import open3d as o3d
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/open3d/__init__.py", line 61, in <module>
    load_cdll(str(next((Path(__file__).parent / "cpu").glob("pybind*"))))
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/open3d/__init__.py", line 38, in load_cdll
    return CDLL(str(path))
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by lucky339aue** [comment]
`sudo apt-get update
sudo apt-get install mesa-utils
`
Solve the problem

**Comment by lucky339aue** [comment]
wandb: Appending key for api.wandb.ai to your netrc file: /home/xingnan_001/.netrc
Thread HandlerThread:wandb.init()...
Traceback (most recent call last):
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 99, in _run
    self._process(record)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 278, in _process
    self._hm.handle(record)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 150, in handle
    handler(record)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 160, in handle_request
    handler(record)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 702, in handle_request_run_start
    self._system_monitor.probe(publish=True)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in probe
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in <listcomp>
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/gpu.py", line 395, in probe
    info["gpu"] = pynvml.nvmlDeviceGetName(pynvml.nvmlDeviceGetHandleByIndex(0))  # type: ignore
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/vendor/pynvml/pynvml.py", line 1962, in wrapper
    return res.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
wandb: ERROR Internal wandb error: file data was not synced
wandb: ERROR transport failed
Traceback (most recent call last):
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 2428, in <module>
    main()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 2421, in main
    neural_graph_map.fit()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 1036, in fit
    run = wandb.init(
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
Traceback (most recent call last):
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 2428, in <module>
    main()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 2421, in main
    neural_graph_map.fit()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/src/neural_graph_mapping/run_mapping.py", line 1036, in fit
    run = wandb.init(
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/xingnan_001/ceshi/neural_graph_mapping/.pixi/envs/default/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
wandb: While tearing down the service manager. The following error has occurred: [Errno 32] Broken pipe

**Comment by lucky339aue** [comment]
The image driver of N card can only be 552.44.

**Comment by lucky339aue** [comment]
成功运行pixi run nrgbd_br --rerun_vis True

**Comment by roym899** [comment]
Can you elaborate what issue you're having? Any Nvidia driver recent enough to support CUDA 12.1 should work. See table 3 [here](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).

Older versions probably also work if you adapt the CUDA / torch versions in pixi.toml accordingly.

**Comment by roym899** [comment]
Closing this issue, since it sounds like you fixed it yourself.
